[package]
name = "sif_test"
version = "0.1.0"
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"

[dependencies]
shalrath = { path = "../shalrath" }
ogre = { path = "../ogre" }
png = "0.16.8"
futures = "0.3.14"
async-std = "1.9.0"